package config

// DevProfile returns a YAML configuration template suitable for local development.
// Security features are relaxed for ease of development.
func DevProfile() string {
	return `# sentinel.yaml — A2A Security Gateway Configuration
# Generated by: sentinel init --profile dev

listen:
  host: 127.0.0.1
  port: 8080
  max_connections: 100
  global_rate_limit: 1000
  trusted_proxies: []
  tls:
    cert_file: ""
    key_file: ""

external_url: http://localhost:8080

mcp:
  enabled: false
  host: 127.0.0.1
  port: 8081
  auth:
    token: ""

health:
  liveness_path: /healthz
  readiness_path: /readyz
  readiness_mode: any_healthy

agents:
  - name: example-agent
    url: http://localhost:9000
    card_path: /.well-known/agent.json
    poll_interval: 60s
    timeout: 30s
    max_streams: 10
    default: true
    allow_insecure: true
    health_check:
      enabled: true
      interval: 30s
    card_change_policy: alert

routing:
  mode: path-prefix

card:
  mode: gateway
  gateway_jwk_file: ""

security:
  card_signature:
    require: false
    trusted_jwks_urls: []
    cache_ttl: 3600s

  auth:
    mode: passthrough-strict
    schemes:
      - type: bearer
        jwt:
          issuer: ""
          audience: ""
          jwks_url: ""
    allow_unauthenticated: true

  replay:
    enabled: false
    window: 300s
    nonce_policy: warn
    nonce_source: auto
    clock_skew: 5s
    store: memory
    redis_url: ""

  rate_limit:
    enabled: false
    ip:
      per_ip: 200
      burst: 50
      cleanup_interval: 5m
    user:
      per_user: 100
      burst: 20
      cleanup_interval: 5m
    per_agent: 500

  push:
    block_private_networks: false
    allowed_domains: []
    require_https: false
    require_challenge: false
    hmac_secret: ""

body_inspection:
  max_size: 1048576
  skip_streaming: true

logging:
  level: debug
  format: json
  output: stdout
  audit:
    sampling_rate: 1.0
    error_sampling_rate: 1.0
    max_body_log_size: 1024

shutdown:
  timeout: 30s
  drain_timeout: 15s

migration:
  agentgateway_version: "latest"
`
}

// ProdProfile returns a YAML configuration template for production deployment.
// All security features are enabled by default.
func ProdProfile() string {
	return `# sentinel.yaml — A2A Security Gateway Configuration
# Generated by: sentinel init --profile prod

listen:
  host: 0.0.0.0
  port: 8080
  max_connections: 1000
  global_rate_limit: 5000
  trusted_proxies: []
  tls:
    cert_file: ""
    key_file: ""

external_url: https://sentinel.example.com

mcp:
  enabled: false
  host: 127.0.0.1
  port: 8081
  auth:
    token: ""

health:
  liveness_path: /healthz
  readiness_path: /readyz
  readiness_mode: any_healthy

agents:
  - name: example-agent
    url: http://localhost:9000
    card_path: /.well-known/agent.json
    poll_interval: 60s
    timeout: 30s
    max_streams: 10
    default: true
    allow_insecure: false
    health_check:
      enabled: true
      interval: 30s
    card_change_policy: alert

routing:
  mode: path-prefix

card:
  mode: gateway
  gateway_jwk_file: ""

security:
  card_signature:
    require: true
    trusted_jwks_urls: []
    cache_ttl: 3600s

  auth:
    mode: passthrough-strict
    schemes:
      - type: bearer
        jwt:
          issuer: ""
          audience: ""
          jwks_url: ""
    allow_unauthenticated: false

  replay:
    enabled: true
    window: 300s
    nonce_policy: warn
    nonce_source: auto
    clock_skew: 5s
    store: memory
    redis_url: ""

  rate_limit:
    enabled: true
    ip:
      per_ip: 200
      burst: 50
      cleanup_interval: 5m
    user:
      per_user: 100
      burst: 20
      cleanup_interval: 5m
    per_agent: 500

  push:
    block_private_networks: true
    allowed_domains: []
    require_https: true
    require_challenge: true
    hmac_secret: ""

body_inspection:
  max_size: 1048576
  skip_streaming: true

logging:
  level: info
  format: json
  output: stdout
  audit:
    sampling_rate: 1.0
    error_sampling_rate: 1.0
    max_body_log_size: 1024

shutdown:
  timeout: 30s
  drain_timeout: 15s

migration:
  agentgateway_version: "latest"
`
}
